set(WSCPP_VERSION 0x010000)
set(WSCPP_VERSION_MAJOR 1)
set(WSCPP_VERSION_MINOR 0)
set(WSCPP_VERSION_REVISION 0)

set(WSCPP_VERSION_STR ${WSCPP_VERSION_MAJOR}.${WSCPP_VERSION_MINOR}.${WSCPP_VERSION_REVISION})
set(WSCPP_VERSION_CSTR \"${WSCPP_VERSION_MAJOR}.${WSCPP_VERSION_MINOR}.${WSCPP_VERSION_REVISION}\")

include_directories( ${CMAKE_BINARY_DIR} include build )

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

set(CMAKE_CXX_FLAGS -std=c++11)

add_definitions( -Wall -O3 -g -DWSCPP_VERSION=${WSCPP_VERSION} -DWSCPP_VERSION_STR=${WSCPP_VERSION_CSTR} )
